# Auslagerung
#bild_in_text.py

#Farben importieren:
import color

rucksack = """

"""


start = color.CBLUE + color.CBOLD + """ 
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkkxddodxO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xoc;,,,,,,;ldO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdc:,'...':oOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxl;'',:cdxx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,..,:oxXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNXXKKKXNWWMMMMMWXxc,...,oKWMMMWWNK0OkxxkO0KKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMN0kdlc:;;;;;:cldkKWMWOl;',:okXMWNXKkdc:;;;;;:coxO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKxc,,,;;:::::::;;,,;lOXOc,.';xNWXOoc:,..';cdxOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWXx:,;::codooolccldocc:;;coc'.;xXNOo;''';;cox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWKo;:lllco0kd0OxxkKkdolllc:;;'.:0Xx:'',;:clkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWKoccoxxkOKWXNWWNNWWNNXKKOddo:',o0d;,,;:coOXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMXkdxkKNNWMMMMMMWWXK0OOkkOOOOkdc,co:,;:ccllooloodxkxdddk0XWMMMMMMMMMMMWXK0OOO00XNWMMMMMMMMM
MMMMMMMMMW0OXXWMMMMMMMN0xolc:;:::;::clool:;:::;;;,'''..'''',,;;,,;:lxKWMMMMMWX0xlc:;,,,;;cdOXWMMMMMM
MMMMMMMMMWKNMMMMMWWW0dc:ccclloodkOO0KKkdooccc::;,''',;,'','''',,,;:;,;dKWMWXkl;,',,:c;;clooxk0XWMMMM
MMMMMMMMMMMMMMMMMW0o::cokxxxx0KXNNN0dl::ooolclkOo::,.'',:dkdddc;,';:c:,c0N0o;,,',lxkKXXNNWWWWNNWMMMM
MMMMMMMMMMMMMMMMNx:;oxxk0KKNNWMWN0o;;cloO0xoldKXXXN0d;..,ckNWWN0Oxl:::c;cxo,.,lxOKNWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXd:clxkOXNMWMMMMNx;;:codd0WNklkNNNWWWWOdc;,'lkkkO0KXKklcc;:,';d0XNK0Okxxkk0XNMMMMMMMM
MMMMMMMMMMMMMMNdcddoOKNMMMMMMMXl,:cldoxOXMW0llXXXWWWKkoc,'..,::::codxkxxl,,ckKOoc:;;,',;;;:lk0NMMMMM
MMMMMMMMMMMMMWkcoOkONMMMMMMMMXo,:ldodOXNNMMXocOWX0kdl:cddc:'.:oxxxxollodl;:xd:,'',:clddxkkkkkkOKNMMM
MMMMMMMMMMMMMXocx0XNMMMMMMMMWk;:clkdkWMMWMMXx:xKxlldddk0KKo;';kNNWNX0Oxol::c;;::cdOKXWMMMMMMMMWXNMMM
MMMMMMMMMMMMM0lokKNMMMMMMMMMNl;lllxKNMMMMMMNk::lok000XWMMWOoc,dXOdolcccoolcc;;;,;:lx0XWMMMMMMMMMMMMM
MMMMMMMMMMMMMOodOXMMMMMMMMMMKc:odx0NMMMMMMMNkc:oOXNWMWMMMMNOc';:;:clodOOolldd:'';,,,,cxKWMMMMMMMMMMM
MMMMMMMMMMMMWKdxXWMMMMMMMMMMKl:ddkNMMMMMMMMNkcckNMMMMMMMMMNd'.;looodx0NXxokXN0c.,;;c;.,:xXWMMMMMMMMM
MMMMMMMMMMMMMXkxKMMMMMMMMMMMNd:ox0WWMMMMMMMNk:c0MMMMMMMMMWO;.;lxxkKXNWM0lkNNWW0:.'cOkl:;;lKWMMMMMMMM
MMMMMMMMMMMMMW0kXMMMMMMMMMMMW0ookXMMWXK0KKXKxclKMMMMMMMMW0:':okKNWMMWMNdl0NNMMWOl;,xNNOoc,dNMMMMMMMM
MMMMMMMMMMMMMMNKXWMMMMMMMMMMMNOxONMMW0xxxkkxdook0KXXWMMMNo,cd0WWMMMMMWOcxNWMMMMNOc'cKWWN0ol0MMMMMMMM
MMMMMMMMMMMMMMMWWMMMMMMMMMMMMMN0ONWXOxdxkkkkxdooooodxOKN0olOXWMMMMMMWKllKMMMMMMWOc':KMMMWXxOWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OdodddxxkkkkxxddddoooxxdkXMMMMMMMWKocOWMMMMMMWO:'lXMMMMMXKWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxddddxoldxxxkkxxkkOkxooood0NMMMMMWKd:xNMMMMMMMNk:;kWWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkxxdxxo,.,dxddxdodddxkkxdoddxKWMMWKd:dNMMMMMMMW0c;xNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kOdol;.   .;loddddooddodxxxxddONN0o:dXWMMMMMMWOllOWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kOkdc.........,codxxxdddddddxxdxOkl:dXMMMMMMWXOx0NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xxxdc'...........;loodddodxxdodxxxdlxNMMMMMMWNXNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWWWWN0xdddo;...'''''''...;lolloolodxdoodxdx0NNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWWWNNNNNXXXXKK0xolllc:;;;;;;;;:;;;:loollooolllooccloloxO0KKKXXXXKKXXXNWWWWWWWWMMMMMMMMM
MMWNNXXKK00KK0kkkkkkkOOOkkOOOkxxxxxddddddxkOOOOOOkkkkkkxxxxxkkxxdooodxkOOOOOkkkkkkOOOkkkkkOO0KXNMMMM
MWN0OkkxxxxkkkkxoooodkkkkkkkkkkOOOOOO00OOOO0OOO0000000000OOO0000OkkxxxxxxxxxxxxxxxxdxxxxxkkkOOKNWMMM
MMMMWWWWWWWWWWNXK000000000000OOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOO0000OOOOO00KKKKKKKXXXNNNWWWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""" + color.CEND






key = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxxkKWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoc:;:c:lKMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:cllxxoxccXMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc:olKMWxoo;kMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;codWMMkoo;oNMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;cxlxXMKolc:ckNMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kxdld0olXMMWKolo;dWM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdoodkOkdxxldNMMMOcx:cNM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkddoodxddoodxxoccloxxxodd;dWM
MMMMMMMMMMMMMMMMMMMMMMMMN0kdooloxkkdoddxOKWMMW0occ::clcckNMM
MMMMMMMMMMMMMMMMMMMMWKkdoooxOkdooddx0NMMMMMMMMMMN0xdddONMMMM
MMMMMMMMMMMMMMMMWXkxdooxOkooddxk0NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMW0kOkdooxOkdoddk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWKko:cldkOdoddk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMWMN0dollxO0kooxk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MWxcollodxOkxdo;oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNl:xOOdodo::::;oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKcco::.,l,';.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMKc:;':;c:cxx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMM0c:;dXklxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMKockWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

"""




schatz = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWWNXK0OkkkkkkOO00KKKXXNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNKOkdoc::::ccccccllllllooodddxxxxxxkkkOO00KKXXNNNNXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNKOxdl:,,;:cc::::::::ccc::ccccccccccccccccccclodkkkxdollloodkOKNWWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWNKkxol;,,,,;;;;;::::cc:::::::::::::::::::::::ldkkxdol:;,,'''''',;ldOKWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMWXOxdl:,';:::::::;;;;;;;;;;;;:::::::::::::::::oxkxdlc:,'............',cdOXWMMMMMMMMMMMMM
MMMMMMMMMMMWKkdoc,',;::::::::::::::;;;;;::::::::::::;:::lkkxdolc;'.................';lxKWWMMMMMMMMMM
MMMMMMMMMMWKxdoc,'',;;;;;::::::::::::;;;:;;;;;;;;;;;;;;lkkddoc:,.....................';cxKWMMMMMMMMM
MMMMMMMMWX0kxdl;,;::;;;;;;;;;;;;:::::::::;::::::::::::dOkddlc:'...............'',,,;;;:cclkNMMMMMMMM
MMMMMMMMNOdxxxddddddddoooollcc:::::::::::::::::::::::dOkddoc:,.......''',,,;:::cccccccccc:oXMMMMMMMM
MMMMMMMMXkdddddddddddxxxxxxxxddddddoooolllcccc:::::;o0Oddocc;.',,,;;::ccccccccccccccccc:clkNMMMMMMMM
MMMMMMMMNOxdddddddddddddddddoooodddxxxxxxxxxdddddoodO0xxdlcc::cccccccccccccccccc:::;;;;;lKWWMMMMMMMM
MMMMMMMMMW0oclllc::ccclooodxxxxddolodddddddddddxxxxxxxxxdlcccccccc::ccccc:::;,,,'....',,lXWMMMMMMMMM
MMMMMMMMMMKdlccc;',''''',,,lkdldOdlloooddddddddddddddddddl:ccccccc::;;,,''...........';;oXMMMMMMMMMM
MMMMMMMMMMXkddol;;::;;;;;,;okl'ckxc,',,,;;:::ccllooodddddl:c::;,,''..................,c:dXMMMMMMMMMM
MMMMMMMMMMNkdddl;;::;;;;:::oOd:oOxc;;;;,,,,'''''''',:llll:;;,........................,c:dXMMMMMMMMMM
MMMMMMMMMMWOdddl;;:::::::::okd:oOdc;;:::::;;;;;;;,,;cccc:;;;'........................,c:dXMMMMMMMMMM
MMMMMMMMMMW0dddl;;:::::::;:lxxdxkxc;::::::::::::::;codoolc::,........................,c:dXMMMMMMMMMM
MMMMMMMMMMWKxddl;;c::::::;:::::cc:;,;::::::::::::::cddddoccc,........................,c:dXMMMMMMMMMM
MMMMMMMMMMMXkddl;,;:::::::::;;;;;;;;:::::::::::;;;;cdxddoccc,........................,c:dXMMMMMMMMMM
MMMMMMMMMMMNOddl;,;;;;;:::::::::;;;;;::;;;;;;;;;;;;cxxddoccc,........................,c:dXMMMMMMMMMM
MMMMMMMMMMMNOddl;,;;;;;::::::::::::::ccccc::::::;;;cxkddoccc,........................,c:dXMMMMMMMMMM
MMMMMMMMMMMW0xdl;;:::;;;;;:::::::::::;;;;;;;;;;;:::lxkxdoccc,........................,c:dXMMMMMMMMMM
MMMMMMMMMMMWKxdl;;::::::::;;;;;:::::::::::::::::::;cxkxdoccc,........................;c:dXMMMMMMMMMM
MMMMMMMMMMMWXkdl;;;;;;;;;;;;;;;;;;;;::::::::::;;;;;cxkxdoccc,....................'',,:c:dXWMMMMMMMMM
MMMMMMMMMMMMXOddoooolllccc:::::::::::::::;;;;;;;;;;:xOxdoccc,............'',,,;;:::::cccxNMMMMMMMMMM
MMMMMMMMMMMMWKOkxxxxddddddddddoooooolllccc::::;;;;;cxkxdoccc,...'',,,;;;::ccc:cclodxkO0KXWMMMMMMMMMM
MMMMMMMMMMMMMWWNNNNXXKK00OOOkkkxxddddddddddddoooooloxxddoccc:;;:::c::cclodxkkOKXNNWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOOkkxxxdddddddddocccccllodxkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXKKK00OOkxkkOKXXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

cave = """
.cooooddooooooooooooooooooooooodoooooolcc:;;,,,,,;;;::cloooooooooooooooooooooooooooooooooddddddddol,
;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OkxdooollllllllooodxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxollllllllllllllllllollc:cokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOolllllllllllllllllllllc:::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxllllllllllllllllllccc:::::::cx0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdllllllllcccccccccccccccccccllllloodxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMMMMWN0dlllllllllccclllllllllllllllllllllllllllodxOKNWMMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMMWWXxlcc:clllllllllllllllllllllllollllllolllllllllox0WMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMMMWKOxc;;,,;:c::::::::cclllllllllllllllllllllccccc:cllxXMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMMMWNOoc:::;;;;;;;;:::cllllllllllllllllllccccc::::::::clldKMMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMMMNKkdollllllc:::::cclllllolllllllllllllllllllllccc::::::coOWMMMMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMWKxolllllollc::::clllllllllllllllllllllllllllllllllcc:::::cokOKNMMMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMMMMNxlllllllllc:cccclllllllcc::;;;;;;,,;;:clllllllllllllllllllllclkXWMMMMMMMMMMMMMMNl
;KMMMMMMMMMMMMMWNN0o::::cccclllllllllcc:;;,,',',,''',,'',,,:lllllllllllllllllllllloxOKWMMMMMMMMMMMNl
;KMMMMMMMMMMMMMNOdc;,;;:cclllllllllc:;,''''''''',,,,,,,,,'',;lllllllllllllllllllcccccokKWMMMMMMMMMNl
;KMMMMMMMMMMMMNOl;;:cllllllllllcc::;,,,'''''''''',,,,'',,,'',:lllllllllllllllllll::::clokXWMMMMMMMNl
;KMMMMMMMMMMMNOocllllllllllccc:::;;,,'''''''.....',,'',',',,';cllllllllllllolllllc::::clldKWMMMMMMNl
;KMMMMMMMMWX0kdollolllccc:::::::;,',,',,''.........'',,''','',:lllllllllllllllllll:::::lloOWMMMMMMNl
;KMMMMMMWXkoollllllllc:::::::;,,,''''...............'',,'','',,;:lllllllllllllllllc::::clldKMMMMMMNl
;KMMMMMWKxllollolllllc::::;,,,','.....................',,'','''';clllllllllllcllllllc::::clkNMMMMMNl
;KMMMMMXxllllllllllc:::;,,,'''''........................''''''''';clllllllc::clllllllc::::coOWMMMMNl
;0MMMMMKdlllllllllc:::;,,'',','.............................'''''';clllllll::lllllllll::::clkNMMMMNl
;0MMMMMKdlllllllc::::;,,,,'','...............................'''',,:llollllc:cllllllllc::::ld0NWMMNl
;0MMMN0xlccllllc:::::;,,,,'',.................................','',;lllllllc:clllcclllc::cclllokXMNl
;KMW0xollcclllll:::::;,,,,'',..................................',',;llllllllcclllc:ccc::cllllc:lOWNl
;0W0ollllccllllc:::::;,'''','..................................''',;cllllllllccllc:::::cllllolc:dXNl
;0WOolllc:clllllc::::;,'''','...................................',',cllllllllc::llc::::cllllllc:l0Xl
;0Xxlllolc:cllllllc::;,,'',,'...................................''',;cllllllllcclllc:::lllllllc:cd0c
,kkollllll::clllllc:::;,'''''.........................''',,'''..',;:clllcclllllllllc::clllllllc::ld:
'lolllllllcclllll::::;,,,''''...................,dkO0KKXXXXXXKkl;:llllllcclllllllllc::cllllllc:::cl,
,dxoolllllllllllccccc;,'',;;::;,,:lloddxxxkkxxxxKWMMMMMMMMMMMWKollllllllcccccccllllc::cllllcccclodx:
;0WX0Oxdolllllllcllllc,,;clllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xooodddollllc:::cccccllllcd0KKXNNWXl
;KMMMMWN0xolllcclllllc::lllllllllcxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkOOkxolcccccoxkOOkxddoxXWMMMMMMNl
;0MMMMMMWKdlllllccclccllllllllllc:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKK0K0OkkkO00OkkxkKWWWXXWMMMMMMMMNl
;0MMMMMMXxolllloxkxdodddooollcccccdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00XWMWWNNNWWMMMMMMMMMMMMMMNl
;0MMMMMMWKOOkkkOKX0OOkkkxdooldkkkkO00KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMNl
;0MMMMMMMMMMMMMWXOOOOOOkdoood0WWXKKK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
,0MMMMMMMMMMMMMMWXKK0OkxxdxxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
'kMMMMMMMMMMMMMMMMMMWWNNNNNWWMWMMMWMMMMMMMMMWWMMMMMMMMMMMMWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
.kMMMMMMMMMMMMMMMMMMMMMMMMMMNK00K0000KKK00KK0KNXKK00KXNWN0O0K00OOO00OOO0NMMMMMMMMMMMMMMMMMMMMMMMMMNl
.dXXXXXXXXXXXXXXXXXXXXXXXXXXKO0OOOOOO000OOOOOO00OOOOO0KXKOO0000OOOO00OOOKXXXXXXXXXXXXXXXXXXXXXXXXX0c
.';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.
"""



boat =  color.CBLUE + """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMW0dONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMW0l..lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl..:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMW0c. .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo..;lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdl, .dNMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXo',..;ONNNNNNNWWWWWWWWWWWWWWWWWWWNNWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWNK0Okxdollcccccc;.';,,:ccccccllllcccccccclllllllllloodk0NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWX0Oxddoc;,,,,;;::::::;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;;;;,,;;:lx0NMMMMMMMMMMMMMM
MMMMMMMMMMMMWN0kdolc;,;;;;;;;;;;;::::::::::::::;;;;;;;:::::::::::::::::::;;:;'''';:::lxXWMMMMMMMMMMM
MMMMMMMMWXOdl:,'',;;;;;;;;:::;;;;,,,,,,,,,,,,',;,;;;;,,,;,,,,,,,,,,,,,,,,,,,'..'''',;;,cd0NMMMMMMMMM
MMMMMMXxl;,',;;;;;:::;;,,,,,,'''''',,,,,,,,,'..,::c:::;,,,'.,,,,,,,,,,,,,,,'.....'''''',,:ld0WMMMMMM
MMMWKo;,,;;;;:;;;;;,,,''',,,,,,,,,,,,,,,,,,,,,...;::::::,...',,,,,,,,,'''',...'......'''',,,:okXWWWM
MMM0:;c;,;:;;;;,,,,,,,,,,,,,,,,,,,,,,,'''.'..''...',:::::,.......................''....''''.,::co0WM
WMMk,,::;;;;'..',,,,,,,,,,,,,''''''''...'...'..'....,:c::,..',,,;;;;,,,,,,,'......''''',,;;;::c:',kM
MMW0;.''',;,,,,,,,,,,,,,,'......''''',,;;;;;:::::::,.':c:,..,:lllllllcccccc:;,,,;;;;;;;;;;;,,,''.,OM
MMWNd,'.''''''',,,,,,;;;,,,,,,,,,,;;::cccccccccccccc;.':;'.,:::cc:::::::;;;;;;,,,,,'''''','''''..lNM
MMMMWKOl'',,''''''''''''',,,,,;,,,;;;;;,,,,,,,,,,,,,;,,,,..';,,,,,,,,,,,,',,'''''''''''',,',,,,.lXMM
MMMMMMWWO:,;;,,,,,'''''''''''''''''''''''''''''''''''''''...,,''''''''',,,,,,,,,,;;;;;;;;;;,;,';0WMM
MMMMMMMMMXd;',,;;;;;;;;,,,,,,,,,,,,,,,'''''''''''''''''''..',,,,,,;;;;;;;;;;;;;;;,,,,,,'',,,,''xWMMM
MMMMMMMMMMWKd;'.,,,;,,,,,,;;;;;::::::::;;;;;;;;;;;;;;;;;,..';;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'lNMMMM
MMMMMMMMMMWMWNOo:'',,,,''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...','',,,,,,,,,,,,,,,,,,,,,,,,,,,,,.:KMMMMM
MMMMMMMMMMMMMWMMNkc,.',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..',,,,,,,,,,,,,,,,,,,'''''''''''...,OWMMMMM
MMMMMMMMMMMMMMMMMMW0d:'....'''......''''''''''''''''''''...'''''''''''''''''............,;:o0WMMMMMM
MMMMMMMMMMMMMMMMMMMWWWKxoc:;,.....................'..''....''..............'',;;:cclodk0KNWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kddddoooolllcccc:::::::;,....,,;::cclloodxkkO0KKXNNWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMWWWWWWWWXd...:OXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.....cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0;.......lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOl,........'OMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo...........kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl..........'OMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc .........,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo..........lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOdc:;,,''lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""" + color.CEND



sword = """

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0O
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.c
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOxl;..;0
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxolc;,;::,:OW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c',,,;:cc;:OWM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:,,,;;;,,'cKMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;,,;;;,'..oXMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:,,;;,','':OWMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc;;;;,....:OWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWX0XWMMMMMMMMMMMMMMWXOdc:::;,'...:kNMMMMMMMMM
MMMMMWWMMMMMMMMMMMMMMMNKxc,'dWMMMMMMMMMMMWKOdl::::;'....ckNMMMMMMMMMMM
KxllllloooddxxkOOKKX0d:,.;oxKMMMMMWNXK0kxoc::c:;,'..':xKWMMMMMMMMMMMMM
c......''',';;,:;;;:;.''';lddxxdddlcc:::clllol;,,:okKWMMMMMMMMMMMMMMMM
Ko,..;cc::;;;,,,'';:;,:::,..',;;::cclloodxxxkxkOKWMMMMMMMMMMMMMMMMMMMM
MMKc.c0NWNXXK0Okd:'..',,;;,;cccccloddodkO0KXWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMXd,,lkKNWWWNXk:;ddl:',dKKXXKXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMWKd;.';:clo:..l0XOl:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMN0dl;',:;....:lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWNKOxddxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


"""

snake = """
MMMMMMMMMMMMMMMWXd,.     ..;cdOKXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWKo'             ..''...',cokKWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMXo.                           .;lxONMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMXc         .....      .,:,.        .kMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNl       .ckKXXK0d;.   .dXNKko,.,'.ckNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMk.      .dWMMMMMMMWOc.  .,dNMW0kXK0WMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNc       :XMMMMMMMMMMWOc.  .;kXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMK,       oWMMMMMMMMMMMMWXOkxlcl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMM0,       lNMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMX:       '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWk.       ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWx.       .:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWk'         'cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWKc.           .,cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMW0o;.             'ck0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKxl;..           .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNXWMMMMMMMMMMMMWX0xl,.          .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMKoOMMMMMMMMMMMMMMMMMNKx:.         'kWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMWk'lWMMMMMMMMMMMMMMMMMMMWKl.        .dWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMWO'.dWMMMMMMMMMMMMMMMMMMMMMWd.        .OMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMKl..lXMMMMMMMMMMMMMMMMMMMMMMMN:         oWMMMMMMMMMMMMMMMMMMMMMMMMM
MWO, .lNMMMMMMMMMMMMMMMMMMMMMMMMNc         :NMMMMMMMMMMMMMMMMMMMMMMMMM
Wx.  lNMMMWXOdlccccclllodkO0KNWWO.         lNMMMMMMMMMMMMMMMMMMMMMMMMM
k.  cXMMWO:.               ...,;.         .l0KKKKK00OkxddoodxOKNMMMMMM
;  ,KMMNo.                                  .......           .'cOWMMM
   :NMMx.                                                        .oNMM
   'OWMx.                                                         .xMM
.   'dOo.                                                          lXM
'                                                                   'd
d.                                                                    
Nk;.                                                                  
MMWKkoc,.                                                            ,
MMMMMMMNOo;.                                    .:ddc,..           .:0
MMMMMMMMMMWKkl:'.                        ..';cokXWMMWNXKOkxoooooodkKWM
MMMMMMMMMMMMMMWX0xc,..             ...;cdk0XWMMMMMMMMMMMMMMMMMMMMMMMMM

"""


rum = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcccdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.....kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.''..oWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,;,'.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNx::;,'.;0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWxcOk:;;'.;0MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMM0:xNd;;;,..cNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWMk'lOl,;;,..,0MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWKdc,,;;;;;,'.':kNWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWd.,okkxxdo:,,'.'kWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMKl'';:clllc:,,,''';xNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNl.,xX0olc;;;,;;,'..'xWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXc':cocco:,;;,,,,....dWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWd,;;:llcccccccc:...,OMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMK:',cl:ll:;::;;;...oNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWx,,::':c,,;:,,...;0MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXl',cddxxddol:...dWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMO,,ol::::;;,'..cXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWx;cxdc;;;;,..:0MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKxxxdolooodkNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""
skull =  color.CRED +'''

                 uu$$$$$$$$$$$uu
              uu$$$$$$$$$$$$$$$$$uu
             u$$$$$$$$$$$$$$$$$$$$$u
            u$$$$$$$$$$$$$$$$$$$$$$$u
           u$$$$$$$$$$$$$$$$$$$$$$$$$u
           u$$$$$$*   *$$$*   *$$$$$$u
           *$$$$*      u$u       $$$$*
            $$$u   0   u$u    0  u$$$
            $$$u      u$$$u      u$$$
             *$$$$uu$$$   $$$uu$$$$*
              *$$$$$$$*   *$$$$$$$*
                u$$$$$$$u$$$$$$$u
                 u$*$*$*$*$*$*$u
      uuu        $$u$ $   $ $u$$       uuu
      u$$$$       $$$$$u$u$u$$$       u$$$$
      $$$$$uu      *$$$$$$$$$*     uu$$$$$$
    u$$$$$$$$$$$uu    *****    uuuu$$$$$$$$$
    $$$$***$$$$$$$$$$uuu   uu$$$$$$$$$***$$$*
     ***      **$$$$$$$$$$$uu **$***
              uuuu **$$$$$$$$$$uuu
     u$$$uuu$$$$$$$$$uu **$$$$$$$$$$$uuu$$$
     $$$$$$$$$$****           **$$$$$$$$$$$*
       *$$$$$*                      **$$$$**
         $$$*                         $$$$*

''' + color.CEND





island = color.CBLUE + color.CBOLD + """            ~        ~          
 ~                                  _.,-'=_.-'-._  ~        ~
         ~     ~           ~   ._.-'             '-._   ~
                      _.-':_.-'                      '-._   ~     ~
                  _.-'                                   '-._.'-._
   ~       .-'.-,'                                                '-.
           '-._                       /\   /\                  _ _.-'
 ~             '-.                   /  \ /  \                ._'
           ~      '-._                /\ (           _.'-._,-'
                      '-._           /  \ )      _.-'   ~   
 ~                ~     .-'               (     .'          ~
      ~     ~         .-'                 )    '-._.,.            ~
   ~       ~     ~     '-._               /           '-._  ~ 
    ~        ~             '-._          (                '.   ~
    ~       ~         ~      .'          )                '-._
   ~     ~  ~     ~       _.-'           /                   _.'   ~
                         '-._           /                   '-._-'-.
                             '-._      (                        _.-'
  ~          ~             ~     '-.    ) /\            _.-"._,'
                  ~              _.'   / /\ /\         '.  ~    (o o)
    (o o)              _.-'-._.-'     / /  \  \          '-._._ ))~((
    ))~(( ~        _.-'              /                         '-. ~
                .-'                 /                             '-.__
 ~            _.'              /\  /    /\                _ _.'-.-'._ .'
     .-'=_.'-'                /\ /\   /\ /\          _.-'     ~   
  _.-'                       /  \  \ /  \  \        '_   ~       ~
.'                                                   '-._   ~    ~
'-.- = .-'.                                              '=._
          '._                                                '-.__
       ~    :_                     START                    _.-'.-' ~ 
     ~     ~   "._,-'.-'._    .-`-.__.._.='._           .-'  ~
                    ~     '-_."  ~           '-._:'=~_.'   ~        ~
  ~                                ) ( ) (  ~     ~     ~      ~
          ~          ~            ) " ( " (
                                 )  "  ("  (    ~     ~       ~     ~ 
          ~     ~               )   "   (   ( ___   ~     ~ 
                                    "   "    |   |           ~                 
   ~     ~       ~     ~     ----._-|--|--|--|--/          ~     ~ 
                                   \ o  o  o  o/     ~     ~       ~     
         ~       ~        ~    ~~~~~~~~~~~~~~~~~ ~     ~       ~     ~ 

""" + color.CEND







compass = color.CBLUE + color.CBOLD + """

        N
        .
        | 
        |
W ------o------- O
        |
        |
        .
        S

""" + color.CEND